server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ddcoreprd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: mes
    password: mes123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
